spring.application.name=DinhHuuMinhLoc

# Kết nối tới service 'db' trong Docker Network
spring.datasource.url=jdbc:mysql://db:3306/dinhhuuminhloc?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username=root
# Thay đổi để nhận từ biến môi trường của Docker Compose, mặc định là 'root'
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

# Tự động tạo bảng dựa trên Entity Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}